# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5.QtMultimedia import QMediaPlayer

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1184, 601)
        Dialog.setStyleSheet("QDialog {\n"
"background-color:#54784E;\n"
"}")
        

        self.video_widget = QVideoWidget(Dialog)
        self.video_widget.setGeometry(QtCore.QRect(80, 30, 480, 270))
        self.video_widget.setObjectName("video_widget")

        self.video_widget.setGeometry(QtCore.QRect(10, 10, 960, 540))
        self.video_widget.setStyleSheet("QGraphicsView {\n"
"  background-color:#D7B8F3;\n"
"}")
        

        self.media_player = QMediaPlayer(Dialog, QMediaPlayer.VideoSurface)
        self.media_player.setObjectName("media_player")
        self.media_player.setVideoOutput(self.video_widget)


        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(980, 20, 191, 531))
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"  background-color: #0d1b2a;\n"
"  border-radius: 12px;\n"
"  padding: 5px;\n"
"}\n"
"\n"
"/* Sekme başlıklarının stilini belirleme */\n"
"QTabBar::tab {\n"
"  background: #1b263b;\n"
"  color: white;\n"
"  padding: 10px;\n"
"  border-top-left-radius: 10px;\n"
"  border-top-right-radius: 10px;\n"
"  margin: 5px;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab:hover {\n"
"  background: #324a67;\n"
"  color: #ffffff;\n"
"}\n"
"\n"
"")
        
        self.progess_bar = QtWidgets.QProgressBar(Dialog)
        self.progess_bar.setGeometry(1010,415, 111,25)
        self.progess_bar.setValue(0)


        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalSlider = QtWidgets.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 130, 160, 16))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(30, 80, 121, 19))
        self.label.setStyleSheet("QLabel {\n"
"\n"
"  color:white;\n"
"}")
        self.label.setObjectName("label")
        self.radioButton_1 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_1.setGeometry(QtCore.QRect(20, 170, 92, 25))
        self.radioButton_1.setStyleSheet("QCRadioButton {\n"
"\n"
"  color:white;\n"
"}")
        self.radioButton_1.setObjectName("radioButton_1")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 210, 92, 25))
        self.radioButton_2.setStyleSheet("QRadioButton {\n"
"\n"
"  color:white;\n"
"}")
        self.radioButton_2.setObjectName("radioButton_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser.setGeometry(QtCore.QRect(20, 270, 141, 71))
        self.textBrowser.setStyleSheet("QTextBrowser {\n"
"\n"
"  color:white;\n"
"  background-color:#6a040f;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(self.tab)
        self.pushButton.setGeometry(QtCore.QRect(20, 390, 141, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"  color:white;\n"
"  background-color:#232E21;\n"
"  border-radius:12px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 66, 19))
        self.label_2.setStyleSheet("QLabel {\n"
"\n"
"  color:white;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(10, 380, 161, 51))
        self.frame.setStyleSheet("QFrame {\n"
"  background-color:white;\n"
"  border-radius:12px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.horizontalSlider.raise_()
        self.label.raise_()
        self.radioButton_1.raise_()
        self.radioButton_2.raise_()
        self.textBrowser.raise_()
        self.pushButton.raise_()
        self.label_2.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 430, 151, 41))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    font: 75 14pt \"Ubuntu Sans\";\n"
"  color:black;\n"
"  background-color:white;\n"
"  border-radius:12px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 10, 161, 391))
        self.textBrowser_2.setStyleSheet("QTextBrowser {\n"
"\n"
"  color:white;\n"
"  background-color:#6a040f;\n"
"}")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Doğruluk eşiği"))
        self.radioButton_1.setText(_translate("Dialog", "resim"))
        self.radioButton_2.setText(_translate("Dialog", "video"))
        self.textBrowser.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Sans\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">ÇIKTILAR İÇİN RUNS KLASÖRÜNÜ KONTROL EDİN</p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "DOSYA SEC"))
        self.label_2.setText(_translate("Dialog", "0"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.pushButton_2.setText(_translate("Dialog", "yukle"))
        self.textBrowser_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu Sans\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Burda kendi modelinizi yükeleyebilir ve bu çıktıları görebilirsiniz modelinizin </span><span style=\" font-size:14pt; font-weight:600;\">YOLOv8</span><span style=\" font-size:14pt;\"> ile uyumlu olması gerekir detaylı bilgi için </span><a href=\"https://docs.ultralytics.com/tr/modes/predict\"><span style=\" font-size:14pt; text-decoration: underline; color:#0000ff;\">buraya </span></a><span style=\" font-size:14pt;\">bakabilirsiniz.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))
